const { Router } = require('express')

const AuthRoutes = require('./AuthRouters.js')
const RoleRoutes = require('./RoleRoutes.js')
const UserRoutes = require('./userRoutes.js')
const PostionRoutes = require('./PostionRoutes.js')
const GovernmentOfficeRoutes = require('./GovernmentOfficeRoutes.js')
const Issue = require('./IssueRouters.js')
const EnumRoutes = require('./EnumValueRouters.js')
const IssueDetails = require('./IssueDetailsRouters.js')
const ComplaintRoutes = require('./ComplaintRouters.js')
const GeneralizationRoutes = require('./GeneralizationRoutes.js')
const DecisionRoutes = require('./DecisionRputers.js')
const LeaveTypeRoutes = require('./LeaveTypeRouters.js')
const EmployRoutes = require('./EmployRouters.js')
const LicenseTypeRoutes = require('./LicenseTypeRoutes.js')
const LicenseRoutes = require('./LicenseRoutes.js')
const LeaveDetailsRoutes = require('./leaveDetailsRouters.js')
const LeaveAllocationRoutes = require('./LeaveAllocationRouters.js')
const CustomerRoutes = require('./CustomerRoutes.js')
const BookRoutes = require('./BookRouters.js')
const BookOrderRoutes = require('./BookOrderRoutes.js')
const TribunalRoutes = require('./TribunalRouters.js')
const StateIssueAgencyRoutes = require('./StateIssueAgencyRouters.js')
const AgencyRoutes = require('./AgencyRouters.js')

const rootRouter = Router()

rootRouter.use('/auth', AuthRoutes)
rootRouter.use('/role', RoleRoutes)
rootRouter.use('/user', UserRoutes)
rootRouter.use('/position', PostionRoutes)
rootRouter.use('/government-office', GovernmentOfficeRoutes)
rootRouter.use('/issue', Issue)
rootRouter.use('/enum', EnumRoutes)
rootRouter.use('/issue-details', IssueDetails)
rootRouter.use('/complaint', ComplaintRoutes)
rootRouter.use('/generalization', GeneralizationRoutes)
rootRouter.use('/decision', DecisionRoutes)
rootRouter.use('/leave-type', LeaveTypeRoutes)
rootRouter.use('/employ', EmployRoutes)
rootRouter.use('/license-type', LicenseTypeRoutes)
rootRouter.use('/license', LicenseRoutes)
rootRouter.use('/leave-details', LeaveDetailsRoutes)
rootRouter.use('/leave-allocation', LeaveAllocationRoutes)
rootRouter.use('/customer', CustomerRoutes)
rootRouter.use('/book', BookRoutes)
rootRouter.use('/book-order', BookOrderRoutes)
rootRouter.use('/tribunal', TribunalRoutes)
rootRouter.use('/state-issue-agency', StateIssueAgencyRoutes)
rootRouter.use('/agency', AgencyRoutes)

module.exports = rootRouter
