name: Run Unit Tests

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
