name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          # Enable caching for npm
          cache: 'npm'
          # Make sure you have a package-lock.json in your repo
          cache-dependency-path: 'package-lock.json'
          
      - name: Install dependencies
        # For a clean, reproducible environment, use npm ci
        run: npm ci
        
      - name: Verify build
        run: npm run build
        
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
